### ISSUE TITLE
Nervous system tissues listed under 'Unnamed' anatomical system

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-bulk#14]
Should 'forebrain and midbrain' not be in 'nervous system'? - see: https://www.ebi.ac.uk/~rpetry/testing/gxa/gxa_issues6.png. In other experiments I've seen other nervuos system examples, all containing 'and' that were listed under the 'Unnamed' anatomical system.

**Comment by alfonsomunozpomer** [comment]
Unforunately, the tissues under each anatomical system doesn’t depend on us, but on curators and OLS. The issue in this case is that there’s no EFO/UBERON term of ‘forebrain and midbrain’. Probably the annotation can be improved or there was no better term at the time.
