### ISSUE TITLE
Gene set enrichment tab is not working properly in Bulk Expression Atlas

### ISSUE THREAD

**Issue by upendrakumbham** [ebi-gene-expression-group/atlas-web-bulk#160]
Currently our only 1 example on the Gene set enrichment tab is not working. It is giving a 400 HTTP status (error).
We have to find out what is causing this.

Steps to reproduce:

1. Go to Bulk Expression Atlas and select Gene set enrichment tab
2. Click on the only 1 example.

Expected behaviour: Result for the Gene set enrichment

Actual behaviour: Error message appears on the screen.

If you click on this URL:
[https://www.ebi.ac.uk/gxa/genesetenrichment?query=AT1G48030%20AT1G53240%20AT2G17130[…]60%20AT4G35650%20AT4G35830%20AT5G03290%20AT5G08300%20AT5G23250](https://www.ebi.ac.uk/gxa/genesetenrichment?query=AT1G48030%20AT1G53240%20AT2G17130%20AT2G20420%20AT2G44350%20AT2G47510%20AT3G09810%20AT3G15020%20AT3G17240%20AT3G27380%20AT3G55410%20AT3G60100%20AT4G26910%20AT4G35260%20AT4G35650%20AT4G35830%20AT5G03290%20AT5G08300%20AT5G23250)

you will get this error:

![Image](https://github.com/ebi-gene-expression-group/atlas-web-bulk/assets/15771356/44dbdbda-07bb-4d52-8485-7b20c2fecdf5)

**Comment by ke4** [comment]
TODO:

- Research the code
- Set up a meeting with the Data Production Team to cooperate with them in this issue

**Comment by ke4** [comment]
For gene set enrichment we are using an external API that is down.
It is a REST service that should be run by our group, but it is currently not up and running.
The API is defined in this line: [GSA_URL_PATTERN](https://github.com/ebi-gene-expression-group/atlas-web-core/blob/0018494ce41d360ab1a1f29f9bd3108ec3912df1/src/main/java/uk/ac/ebi/atlas/utils/GeneSetEnrichmentClient.java#L31) : https://www.ebi.ac.uk/fg/gsa/api/tsv/getOverlappingComparisons/{0}/{1}
where 
- 0: name of the species
- 1: bioentity identifiers separated by spaces

**Comment by ke4** [comment]
@pmb59 sent a request to get access for codon-plantain-01 VM.
If we have access we can check what is on that VM and we can plan further from that point.

**Comment by ke4** [comment]
Old repo: https://github.com/gxa/atlas_gsa/
The REST API code is accessible here: https://github.com/ebi-gene-expression-group/atlas-prod/tree/develop/analysis/gsa
Confluence is here: https://www.ebi.ac.uk/seqdb/confluence/pages/viewpage.action?spaceKey=GXA&title=REST+APIs

**Comment by ke4** [comment]
The new VM where Data Prod Team is going to run that REST API service is: codon-plantain-01.
They are going to configure a shell script to run that service.
Inside the VPN network it is going to be available like this:
http://codon-plantaion:3001/tsv/getOverlappingComparisons/{0}/{1}

**Comment by ke4** [comment]
We probably have a mapping in EBI's Traffic Manager from
https://www.ebi.ac.uk/fg/gsa/api/ --> http://plantain:3001/
Or something similar.
We or the Data Prod team have to request Systems Team to change that to:
https://www.ebi.ac.uk/fg/gsa/api/ --> http://codon-plantain-01:3001/ (edited)

**Comment by ke4** [comment]
On the latest meeting with WP Team we got the instruction that we have to move this GSA service from codon-plantain-01 VM to a WP VM.
This service is small so, we decided to move it for our already existing VMs and have an instance on all our environments (test, staging, fallback and public).
Pedro is going to start the testing with probably the test environment.
I already updated the ticket regarding the Traffic Manager mapping to point it to those VMs.
I also created a new ticket to replace the hard coded URL to this service and call the service instance in the relevant environment: [Change the hardcoded URL for the GSA REST API in Bulk Expression Atlas](https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/167).

**Comment by ke4** [comment]
I am closing this ticket as it was more a research type ticket.
We gathered all the information that was related to this missing service and split the task.
We are tracking our (we dev) task in this new ticket: [Change the hardcoded URL for the GSA REST API in Bulk Expression Atlas](https://github.com/ebi-gene-expression-group/atlas-web-bulk/issues/167)
