### ISSUE TITLE
[HelpDesk] There seems a 1000-record limit for Differential expression

### ISSUE THREAD

**Issue by ke4** [ebi-gene-expression-group/atlas-web-bulk#169]
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=719456

Copied description from the HelpDesk ticket:

I am trying to query differential expression results for multiple genes.
There seems a 1000-record limit for showing the results as well as for "Download results".

I tried input 
- (i) "AT3G14150" and 
- (ii) "AT2G30970 AT5G19550 AT5G11520 AT1G62800 AT4G31990 AT2G22250 AT4G33680 AT2G13810 AT1G51720  AT3G44310 AT3G44300 AT3G44320 AT5G22300 AT4G08790 AT5G08100 AT3G14130 AT3G14150" 

in hompage. 

With input (i) I got 39 records for Differential expression (smallest |log2FC|=1 as described in FAQ). 
With input (ii) I got a total of 1000 records, where AT3G14150 got only 17 records (smallest |log2FC|=1.4). 

Inputting other long lists got the same 1000-record limit. 

Is there any way for multi-gene queries to get all results |log2FC|>1? 

P.S. I am afraid that, if the 1000-record limit is true, there might be some single gene for some species would reach this limit.

**Comment by lingyun1010** [comment]
User is testing this gene search with (ii) input  https://www.ebi.ac.uk/gxa/search?geneQuery=%5B%7B%22value%22%3A%22AT3G14150%22%7D%2C%7B%22value%22%3A%22AT2G30970%22%7D%2C%7B%22value%22%3A%22AT5G19550%22%7D%2C%7B%22value%22%3A%22AT5G11520%22%7D%2C%7B%22value%22%3A%22AT1G62800%22%7D%2C%7B%22value%22%3A%22AT4G31990%22%7D%2C%7B%22value%22%3A%22AT2G22250%22%7D%2C%7B%22value%22%3A%22AT4G33680%22%7D%2C%7B%22value%22%3A%22AT2G13810%22%7D%2C%7B%22value%22%3A%22AT1G51720%22%7D%2C%7B%22value%22%3A%22AT3G44310%22%7D%2C%7B%22value%22%3A%22AT3G44300%22%7D%2C%7B%22value%22%3A%22AT3G44320%22%7D%2C%7B%22value%22%3A%22AT5G22300%22%7D%2C%7B%22value%22%3A%22AT4G08790%22%7D%2C%7B%22value%22%3A%22AT5G08100%22%7D%2C%7B%22value%22%3A%22AT3G14130%22%7D%2C%7B%22value%22%3A%22AT3G14150%22%7D%5D&species=&conditionQuery=%5B%5D&bs=%7B%22arabidopsis%20thaliana%22%3A%5B%22ORGANISM_PART%22%5D%7D&ds=%7B%22kingdom%22%3A%5B%22plants%22%5D%7D#differential

**Comment by lingyun1010** [comment]
There is a limit in our server for the response length unfortunately to maintain the overall performance. Currently, I am afraid that we do not support any longer than that. We can check the configuration by runnning  `docker run -it --rm tomcat:9-jdk11 cat /usr/local/tomcat/conf/server.xml`
