### ISSUE TITLE
Incorrect date listed in the downloads tab

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-bulk#21]
On https://www.ebi.ac.uk/gxa/download.html, the date against the latest download is for the penultimate release, not the latest - see: https://www.ebi.ac.uk/~rpetry/testing/gxa/gxa_issues14.png

**Comment by alfonsomunozpomer** [comment]
This was a hard-coded value. We’ve fixed this in the latest release and the details of the file are retrieved from the FTP file and in sync with current data.
