### ISSUE TITLE
Gramene Genome Browser defaults to EG Browser?

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-bulk#24]
On https://www.ebi.ac.uk/gxa/experiments/E-GEOD-25759/Results, whether I select Gramene Genome Browser or EG Browser, I get re-directed to https://plants.ensembl.org

**Comment by alfonsomunozpomer** [comment]
We had [a bug which was fixed upstream in the heatmap repository](https://github.com/ebi-gene-expression-group/atlas-heatmap/pull/23) and integrated in the latest release.
