### ISSUE TITLE
One of example queries in FAQs causes server error

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-bulk#25]
The query: https://www.ebi.ac.uk/gxa/search?geneQuery=[{"value":"zinc finger"}]&organism=Mus musculus#differential (mentioned on https://www.ebi.ac.uk/gxa/FAQ.html) returns server error: https://www.ebi.ac.uk/~rpetry/testing/gxa/gxa_issues17.png

**Comment by alfonsomunozpomer** [comment]
I couldn’t reproduce this one. From the error message in the screenshot it looks like a Solr outage. We have now taken measures to minimise service downtime.
