### ISSUE TITLE
Server error for "zinc finger" query

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-bulk#27]
Query: https://www.ebi.ac.uk/gxa/search?geneQuery=%5B%7B%22value%22%3A%22zinc+finger%22%7D%5D&species=&conditionQuery=%5B%5D returned server error: https://www.ebi.ac.uk/~rpetry/testing/gxa/gxa_issues17.png

**Comment by alfonsomunozpomer** [comment]
This query seems to be working now. I suppose it was a transient network/server issue.
