### ISSUE TITLE
A rouge string at the top of the species selection dropdown

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-bulk#28]
A funny string appears at the top of the species selection dropdown on the home page: https://www.ebi.ac.uk/~rpetry/testing/gxa/gxa_issues19.png

**Comment by alfonsomunozpomer** [comment]
This encoding bug has been fixed [in our latest release](https://github.com/ebi-gene-expression-group/atlas-web-bulk/releases/tag/32.0.0).
