### ISSUE TITLE
Genome Browser selection header shown as a selectable option - confusing..

### ISSUE THREAD

**Issue by datasome** [ebi-gene-expression-group/atlas-web-bulk#31]
On e.g. https://www.ebi.ac.uk/gxa/experiments/E-MTAB-2836/Results, when I click on 'Select genome browser to view tracks' I see 2 options to select (c.f. https://www.ebi.ac.uk/~rpetry/testing/gxa/gxa_issues22.png) , one of which is 'Select genome browser to view tracks' itself and doesn't do anything if I select it. Including it as a selectable item is confusing - only 'Ensembl genome browser' should be selectable.

**Comment by alfonsomunozpomer** [comment]
The item ‘Select genome browser’ has been removed [in our latest release](https://github.com/ebi-gene-expression-group/atlas-web-bulk/releases/tag/32.0.0).
