### ISSUE TITLE
Selecting single gene symbol and then pressing Apply has an odd behaviour

### ISSUE THREAD

**Issue by pcm32** [ebi-gene-expression-group/atlas-web-bulk#57]
I noticed that when I add a single gene symbol on the filtering part on the left on the experiment view:

https://wwwdev.ebi.ac.uk/gxa/experiments/E-ENAD-33/Results

and then press "Apply", it complete shuts off the results of the experiment instead of showing a heatmap with a single gene (or warning that you need more than one gene if that is the intended behaviour).

![image](https://user-images.githubusercontent.com/368478/75043569-364db780-54b8-11ea-9f84-f894218b8915.png)

The result of pressing Apply there is:

![image](https://user-images.githubusercontent.com/368478/75043701-6301cf00-54b8-11ea-9afd-dd7c4077e645.png)

**Comment by pcm32** [comment]
To add that this doesn't happen when you select more than one gene symbol.

**Comment by alfonsomunozpomer** [comment]
This is a data issue. We’ll apply a patch to disable boxplots for human or other species until this is fixed.
