### ISSUE TITLE
Summary pdf for proteomics experiments

### ISSUE THREAD

**Issue by Ananth-Prakash** [ebi-gene-expression-group/atlas-web-bulk#80]
Hi,

The PRIDE team has provided pdf documents for most datasets, which describe basic information about the dataset, author contacts, quality assessments of samples and the results of the assessments in the form of plots and tables. Please could this summary pdf document be made available to download in the webpage together with the results.

**Comment by pcm32** [comment]
https://www.pivotaltracker.com/story/show/175232742

**Comment by pcm32** [comment]
This story has been started some weeks ago and we expect a merge soon. @lingyun1010 when you have the PR, please add it here or mention the issue in the PR. Thanks.

**Comment by pcm32** [comment]
On this line, also Juan asked if we could do the MaxQuant files:

> This is a new request, but it would be good to have the MaxQuant output files (for DDA datasets only) linked from there. 

I suspect that this is similar enough to be added on the same story @lingyun1010 ? Thanks. I'll ask for details of the file names.

**Comment by pcm32** [comment]
These are the file names (which will be available only for certain proteomics experiments):

- [x] the unprocessed raw output file (proteinGroups.txt), which is output from MaxQuant before processing and submission into EA.

- [x] Experimental design template, which has the MS raw file annotations and 

- [x] the parameter file (mqpar.xml), which has all input parameters to run MaxQuant, to be also available for download in the Downloads tab along with the other files. These two files are currently not shared.

**Comment by pcm32** [comment]
These are now available, so closing.
